version: '3.5'

services:
  # Backend service
  mariadb:
    image: mariadb:10.7.1
    container_name: esgi_todo_mariadb
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: Europe/Paris
      DEBIAN_FRONTEND: noninteractive
    ports:
      - "3306:3306"
      
  phpmyadmin:
    image: phpmyadmin:5.1.1
    container_name: esgi_todo_phpmyadmin
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - 9000:80

  php-fpm:
    image: php:8.1.6-apache-buster
    build: ../.docker/build/php-fpm
    container_name: esgi_todo_php-fpm
    working_dir: /var/www/
    environment:
      TZ: Europe/Paris
      DEBIAN_FRONTEND: noninteractive
    ports:
      - 3000:80
    volumes:
      - ./:/var/www:cached
      - ../.docker/conf/php-fpm/apache2.conf:/etc/apache2/apache2.conf
      - ../.docker/conf/php-fpm/sites-enabled/:/etc/apache2/sites-enabled

  composer:
    image: composer:2
    container_name: esgi_todo_composer
    command: /bin/sh -c "composer install"
    depends_on:
      - php-fpm
    volumes: 
      - ./:/app:cached